spring.application.name=order-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/order_service}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:order_service_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rgbXYZ@9182}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

server.port=8084

spring.task.scheduling.pool.size=2
spring.task.scheduling.thread-name-prefix=outbox-publisher-

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
