spring.application.name=product-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/product_service}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:product_service_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rgbXYZ@9182}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

server.port=8082

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
